# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f70e147ef0fb0eff5e3a87401a515c0f75be04b4a16dd5bab06eff31bb6c8b22f3f3d6dc89ee03778b0a19f3b829e7c7ced1b193960f73cfffaf070d8fadb24

test:
  secret_key_base: 4b246ea4dce0bc8f123f01b590cf715c51e46c9ef5794d73082aace6a90459e7e30f0d1fdbd485f2429077935f4f76b52dee7902178cffa2104b0ac1b29e7850

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
